package com.example.librarymanagementstudent.model;

import com.example.librarymanagementstudent.Enum.CardStatus;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.hibernate.annotations.CreationTimestamp;

import java.sql.Date;

@FieldDefaults(level = AccessLevel.PRIVATE)
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Entity

public class LibraryCard {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Automatically Generated by database
     int id;

    String cardNo;

    @Enumerated(EnumType.STRING)
    CardStatus cardStatus;

    @CreationTimestamp
    Date issueDate;

    // Uni directional relationship / child connect to the parent
    @OneToOne    // current class to Connecting class / library to student
    @JoinColumn   // it will create a foreign key column and by default it will pick the primary key by default
    Student student;
}
